- name: Sping Vagrant Centos 7 VM
  hosts: localhost
  connection: local 

  vars_files:
    - vars/vm_details.yml

  tasks:
   # - name: Install packages
   #   apt:
   #     name: "{{ item }}"
   #     state: present
   #   become: true
   #   with_items:
   #     - git
   #    # - virtualbox
   #    # - vagrant
    
    - name: Create dir for Vagrant config files
      file:
        state: directory
        path: ./vm      

    - name: Create Vagrantfile from template
      template:
        src: "{{ playbook_dir }}/templates/Vagrantfile.j2"
        dest: ./vm/Vagrantfile
     
    - name: Deploy VM
      command: vagrant up
      args:
        chdir: ./vm/

    - name: Update inventory
      template:
        src: "{{ playbook_dir }}/templates/host.j2"
        dest: "{{ playbook_dir }}/host"
  
    - name: Refresh inventory
      meta: refresh_inventory

- name: Configure VM
  hosts: ocp_host
  become: true
  connection: ssh
  remote_user: vagrant
  vars:
    ansible_ssh_private_key_file: ./vm/.vagrant/machines/default/virtualbox/private_key
  
  vars_files:
    - vars/vm_details.yml

  tasks:
    - name: Update packages
      shell: yum update -y 

    - name: Install packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - git
        - ansible
        - vim
        - wget
        - httpd
        
    - name: Start service httpd, if not running
      service:
        name: httpd
        state: started
...
