- name: Sping Vagrant Centos 7 VM
  hosts: localhost
  connection: ssh 

  vars_files:
    - vars/vm_details.yml
    - vars/vault.yml


  tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
      become: true
      with_items:
        - git
        - virtualbox
        - vagrant
    
    - name: Create dir for Vagrant config files
      file:
        state: directory
        path: ./vm      

    - name: Create Vagrantfile from template
      template:
        src: "{{ playbook_dir }}/templates/Vagrantfile.j2"
        dest: ./vm/Vagrantfile
     
    - name: Deploy VM
      command: vagrant up
      args:
        chdir: ./vm/
...
